//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamDetail()
        {
            this.Scores = new HashSet<Score>();
            this.Scores1 = new HashSet<Score>();
        }
    
        public int ExamDetailID { get; set; }
        public string ExamPlace { get; set; }
        public System.DateTime ExamHour { get; set; }
        public int ExamID { get; set; }
        public int StudentDetailID { get; set; }
        public Nullable<int> Exam_ExamID { get; set; }
        public Nullable<int> StudentDetail_StudentDetailID { get; set; }
        public Nullable<int> LessonDetail_LessonDetailID { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Exam Exam1 { get; set; }
        public virtual LessonDetail LessonDetail { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
        public virtual StudentDetail StudentDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores1 { get; set; }
    }
}
