//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManagerDetail()
        {
            this.TeacherDetails = new HashSet<TeacherDetail>();
            this.SchoolDetails = new HashSet<SchoolDetail>();
        }
    
        public int ManagerDetailID { get; set; }
        public string ManagerEmail { get; set; }
        public string ManagerPhoneNumber { get; set; }
        public string ManagerAddress { get; set; }
        public byte[] ManagerPhoto { get; set; }
        public int ManagerID { get; set; }
    
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherDetail> TeacherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolDetail> SchoolDetails { get; set; }
    }
}
