//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreID { get; set; }
        public int ScoreNumber { get; set; }
        public int LessonDetailID { get; set; }
        public int StudentDetailID { get; set; }
        public int ExamDetailID { get; set; }
        public Nullable<int> StudentDetail_StudentDetailID { get; set; }
        public Nullable<int> ExamDetail_ExamDetailID { get; set; }
        public Nullable<int> LessonDetail_LessonDetailID { get; set; }
    
        public virtual ExamDetail ExamDetail { get; set; }
        public virtual ExamDetail ExamDetail1 { get; set; }
        public virtual LessonDetail LessonDetail { get; set; }
        public virtual LessonDetail LessonDetail1 { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
        public virtual StudentDetail StudentDetail1 { get; set; }
    }
}
